2024-07-31 18:09:21,919 - backend.services.authentication_services - ERROR - Refresh Token function exception: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 95, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 49, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 18:09:21,919 - backend.services.authentication_services - ERROR - Login Required Exception: 500: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 95, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 49, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 101, in decorator
    return refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 78, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 18:11:29,200 - backend.services.authentication_services - ERROR - Refresh Token function exception: read_categories() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return fn(response)
TypeError: read_categories() missing 1 required positional argument: 'response'
2024-07-31 18:11:29,200 - backend.services.authentication_services - ERROR - Login Required Exception: 500: read_categories() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return fn(response)
TypeError: read_categories() missing 1 required positional argument: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 99, in decorator
    return refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 76, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: read_categories() missing 1 required positional argument: 'response'
2024-07-31 18:50:59,302 - backend.services.authentication_services - ERROR - Refresh Token function exception: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 48, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 18:50:59,302 - backend.services.authentication_services - ERROR - Login Required Exception: 500: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 48, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 77, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 19:31:28,533 - backend.services.authentication_services - ERROR - Refresh Token function exception: read_categories() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 69, in refresh_token
    return fn(request)
TypeError: read_categories() missing 1 required positional argument: 'response'
2024-07-31 19:31:28,634 - backend.services.authentication_services - ERROR - Login Required Exception: 500: read_categories() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 69, in refresh_token
    return fn(request)
TypeError: read_categories() missing 1 required positional argument: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 77, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: read_categories() missing 1 required positional argument: 'response'
2024-07-31 19:31:44,723 - backend.services.authentication_services - ERROR - Refresh Token function exception: read_categories() got multiple values for argument 'request'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 69, in refresh_token
    return fn(request, response, **kwargs)
TypeError: read_categories() got multiple values for argument 'request'
2024-07-31 19:31:44,723 - backend.services.authentication_services - ERROR - Login Required Exception: 500: read_categories() got multiple values for argument 'request'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 69, in refresh_token
    return fn(request, response, **kwargs)
TypeError: read_categories() got multiple values for argument 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 77, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: read_categories() got multiple values for argument 'request'
2024-07-31 19:43:25,759 - backend.services.authentication_services - ERROR - Refresh Token function exception: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 47, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 19:43:25,759 - backend.services.authentication_services - ERROR - Login Required Exception: 500: 'coroutine' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 47, in refresh_token
    response.set_cookie(
AttributeError: 'coroutine' object has no attribute 'set_cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 77, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'coroutine' object has no attribute 'set_cookie'
2024-07-31 19:44:13,412 - backend.services.authentication_services - ERROR - Refresh Token function exception: 'list' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 47, in refresh_token
    response.set_cookie(
AttributeError: 'list' object has no attribute 'set_cookie'
2024-07-31 19:44:13,412 - backend.services.authentication_services - ERROR - Login Required Exception: 500: 'list' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 47, in refresh_token
    response.set_cookie(
AttributeError: 'list' object has no attribute 'set_cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 77, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'list' object has no attribute 'set_cookie'
2024-07-31 19:46:12,172 - backend.services.authentication_services - ERROR - Refresh Token function exception: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:46:12,172 - backend.services.authentication_services - ERROR - Login Required Exception: 500: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 99, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 76, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:48:34,953 - backend.services.authentication_services - ERROR - Refresh Token function exception: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:48:34,956 - backend.services.authentication_services - ERROR - Login Required Exception: 500: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 76, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:50:09,820 - backend.services.authentication_services - ERROR - Refresh Token function exception: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:50:09,820 - backend.services.authentication_services - ERROR - Login Required Exception: 500: create_category() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 94, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(request, response)
TypeError: create_category() missing 1 required positional argument: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 100, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 76, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: create_category() missing 1 required positional argument: 'response'
2024-07-31 19:54:16,058 - backend.services.authentication_services - ERROR - Refresh Token function exception: 500: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\category_controller.py", line 85, in update_category
    response_data = category_services.admin_update_category(
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\category_services.py", line 158, in admin_update_category
    logger.info(f"Updating subcategory with ID {category_update_dto.subcategory_id}")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydantic\main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(**kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\category_controller.py", line 92, in update_category
    ApplicationServices.handle_exception(exception, is_raise=True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'
2024-07-31 19:54:16,403 - backend.services.authentication_services - ERROR - Login Required Exception: 500: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 93, in decorator
    data = jwt.decode(accesstoken, AuthenticationEnum.SECRET_KEY, algorithms=["HS256"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jwt\api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\category_controller.py", line 85, in update_category
    response_data = category_services.admin_update_category(
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\category_services.py", line 158, in admin_update_category
    logger.info(f"Updating subcategory with ID {category_update_dto.subcategory_id}")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydantic\main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 68, in refresh_token
    return await fn(**kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\category_controller.py", line 92, in update_category
    ApplicationServices.handle_exception(exception, is_raise=True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 99, in decorator
    return await refresh_token(fn, **kwargs)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 76, in refresh_token
    return ApplicationServices.handle_exception(exception, True)
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\app_services.py", line 36, in handle_exception
    raise HTTPException(status_code=response['status_code'], detail=response['response_message'])
fastapi.exceptions.HTTPException: 500: 'CategoryUpdateDTO' object has no attribute 'subcategory_id'
