2024-08-13 13:50:41,337 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:51:42,023 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 2 required positional arguments: 'response' and 'request'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 2 required positional arguments: 'response' and 'request'
2024-08-13 13:52:17,957 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'request'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 65, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'request'
2024-08-13 13:52:41,919 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Request' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 65, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 239, in app_login
    response.set_cookie(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'set_cookie'
2024-08-13 13:53:11,785 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: name 'request' is not defined
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 67, in user_login
    request)
    ^^^^^^^
NameError: name 'request' is not defined
2024-08-13 13:53:31,266 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:53:48,062 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:54:11,598 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:55:42,184 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:55:54,633 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:57:37,951 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:57:39,946 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:57:40,504 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 13:57:41,185 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 14:02:11,643 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 14:02:12,410 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 64, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() missing 1 required positional argument: 'response'
2024-08-13 14:06:06,826 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'BackgroundTasks' object has no attribute 'set_cookie'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 67, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 238, in app_login
    response.set_cookie(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'BackgroundTasks' object has no attribute 'set_cookie'
2024-08-13 14:06:23,875 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() got multiple values for argument 'background_task'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 67, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() got multiple values for argument 'background_task'
2024-08-13 14:06:51,475 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: AuthenticationServices.app_login() got multiple values for argument 'background_task'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 67, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthenticationServices.app_login() got multiple values for argument 'background_task'
2024-08-20 15:43:15,517 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 69, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 260, in app_login
    value=jwt.encode({
          ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2024-08-20 15:44:44,573 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 69, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 260, in app_login
    value=jwt.encode({
          ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2024-08-20 15:45:04,041 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 69, in user_login
    response_data = authentication_services.app_login(email,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\FastAPI\Structural FastAPI\backend\services\authentication_services.py", line 260, in app_login
    value=jwt.encode({
          ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2024-08-20 18:22:47,842 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'cookies'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 76, in user_login
    accesstoken = response.cookies.get(
                  ^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'cookies'
2024-08-20 18:24:28,857 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'content'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 76, in user_login
    accesstoken = response.content
                  ^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'content'
2024-08-20 18:26:06,089 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'MutableHeaders' object is not callable
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 76, in user_login
    accesstoken = response.headers()
                  ^^^^^^^^^^^^^^^^^^
TypeError: 'MutableHeaders' object is not callable
2024-08-20 18:26:29,072 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'bytes' object is not callable
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 76, in user_login
    accesstoken = response.body()
                  ^^^^^^^^^^^^^^^
TypeError: 'bytes' object is not callable
2024-08-21 11:13:40,734 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'get'
2024-08-21 11:13:59,773 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'get'
2024-08-21 12:31:01,434 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2024-08-21 12:31:03,387 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2024-08-21 12:31:20,292 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2024-08-21 12:32:03,405 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'get'
2024-08-21 12:32:03,655 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'get'
2024-08-21 12:32:03,905 - backend.api.controller.authentication_controller - ERROR - Login validate Controller exception: 'Response' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\Training\FastAPI\Structural FastAPI\backend\api\controller\authentication_controller.py", line 74, in user_login
    response.status_code = response_data.get('status_code')
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'get'
